name: JavaCPP Android NDK Build (r29)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout JavaCPP-Presets Source
      # We check out the source code for javacpp-presets into a subdirectory
      uses: actions/checkout@v4
      with:
        repository: bytedeco/javacpp-presets
        path: javacpp-presets

    - name: Set up JDK 17
      # Java 17 is recommended for modern Java builds
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: actions/setup-maven@v4
      with:
        maven-version: '3.9.6'
      
    - name: Download and Setup Android NDK r29
      # This action automatically downloads and sets up the specified NDK version
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r29
        add-to-path: false # We will explicitly set ANDROID_NDK_HOME
  
    - name: Set ANDROID_NDK_HOME Environment Variable
      # Set the NDK path retrieved from the setup-ndk action output
      run: |
        echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

    - name: Build OpenCV and FFmpeg for ${{ matrix.arch }}
      # Run the Maven build inside the javacpp-presets directory
      run: |
        cd javacpp-presets
        mvn clean install \
          -Djavacpp.platform=${{ matrix.arch }} \
          -Djavacpp.platform.root=${{ env.ANDROID_NDK_HOME }} \
          --projects opencv,ffmpeg \
          -Dmaven.test.skip=true \
          -T 1C # Limit to 1 core per module to stabilize the native compilation process

    - name: Upload Build Artifacts (${{ matrix.arch }})
      # Save the generated JAR files as workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: javacpp-android-binaries-${{ matrix.arch }}
        path: |
          javacpp-presets/opencv/target/*.jar
          javacpp-presets/ffmpeg/target/*.jar
        retention-days: 7
